# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from assistive_msgs/TagDepthObservation.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class TagDepthObservation(genpy.Message):
  _md5sum = "4196ac7d305dd54a89c13071539bb080"
  _type = "assistive_msgs/TagDepthObservation"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 id
geometry_msgs/Point center_cam
geometry_msgs/Vector3 normal_cam
float32 mean_depth_m
float32 valid_point_ratio
uint32 support_point_count
bool plane_fitted

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['id','center_cam','normal_cam','mean_depth_m','valid_point_ratio','support_point_count','plane_fitted']
  _slot_types = ['int32','geometry_msgs/Point','geometry_msgs/Vector3','float32','float32','uint32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,center_cam,normal_cam,mean_depth_m,valid_point_ratio,support_point_count,plane_fitted

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TagDepthObservation, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.center_cam is None:
        self.center_cam = geometry_msgs.msg.Point()
      if self.normal_cam is None:
        self.normal_cam = geometry_msgs.msg.Vector3()
      if self.mean_depth_m is None:
        self.mean_depth_m = 0.
      if self.valid_point_ratio is None:
        self.valid_point_ratio = 0.
      if self.support_point_count is None:
        self.support_point_count = 0
      if self.plane_fitted is None:
        self.plane_fitted = False
    else:
      self.id = 0
      self.center_cam = geometry_msgs.msg.Point()
      self.normal_cam = geometry_msgs.msg.Vector3()
      self.mean_depth_m = 0.
      self.valid_point_ratio = 0.
      self.support_point_count = 0
      self.plane_fitted = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i6d2fIB().pack(_x.id, _x.center_cam.x, _x.center_cam.y, _x.center_cam.z, _x.normal_cam.x, _x.normal_cam.y, _x.normal_cam.z, _x.mean_depth_m, _x.valid_point_ratio, _x.support_point_count, _x.plane_fitted))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.center_cam is None:
        self.center_cam = geometry_msgs.msg.Point()
      if self.normal_cam is None:
        self.normal_cam = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 65
      (_x.id, _x.center_cam.x, _x.center_cam.y, _x.center_cam.z, _x.normal_cam.x, _x.normal_cam.y, _x.normal_cam.z, _x.mean_depth_m, _x.valid_point_ratio, _x.support_point_count, _x.plane_fitted,) = _get_struct_i6d2fIB().unpack(str[start:end])
      self.plane_fitted = bool(self.plane_fitted)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i6d2fIB().pack(_x.id, _x.center_cam.x, _x.center_cam.y, _x.center_cam.z, _x.normal_cam.x, _x.normal_cam.y, _x.normal_cam.z, _x.mean_depth_m, _x.valid_point_ratio, _x.support_point_count, _x.plane_fitted))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.center_cam is None:
        self.center_cam = geometry_msgs.msg.Point()
      if self.normal_cam is None:
        self.normal_cam = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 65
      (_x.id, _x.center_cam.x, _x.center_cam.y, _x.center_cam.z, _x.normal_cam.x, _x.normal_cam.y, _x.normal_cam.z, _x.mean_depth_m, _x.valid_point_ratio, _x.support_point_count, _x.plane_fitted,) = _get_struct_i6d2fIB().unpack(str[start:end])
      self.plane_fitted = bool(self.plane_fitted)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i6d2fIB = None
def _get_struct_i6d2fIB():
    global _struct_i6d2fIB
    if _struct_i6d2fIB is None:
        _struct_i6d2fIB = struct.Struct("<i6d2fIB")
    return _struct_i6d2fIB
