# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from assistive_msgs/TagDetection.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class TagDetection(genpy.Message):
  _md5sum = "be3ec919f3e7b8dc86da70562d16b37e"
  _type = "assistive_msgs/TagDetection"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 id
string dictionary_name
geometry_msgs/Point32[] corners_px
geometry_msgs/Point32 center_px
float32 tag_area_px
float32 detection_score

================================================================================
MSG: geometry_msgs/Point32
# This contains the position of a point in free space(with 32 bits of precision).
# It is recommeded to use Point wherever possible instead of Point32.  
# 
# This recommendation is to promote interoperability.  
#
# This message is designed to take up less space when sending
# lots of points at once, as in the case of a PointCloud.  

float32 x
float32 y
float32 z"""
  __slots__ = ['id','dictionary_name','corners_px','center_px','tag_area_px','detection_score']
  _slot_types = ['int32','string','geometry_msgs/Point32[]','geometry_msgs/Point32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,dictionary_name,corners_px,center_px,tag_area_px,detection_score

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TagDetection, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.dictionary_name is None:
        self.dictionary_name = ''
      if self.corners_px is None:
        self.corners_px = []
      if self.center_px is None:
        self.center_px = geometry_msgs.msg.Point32()
      if self.tag_area_px is None:
        self.tag_area_px = 0.
      if self.detection_score is None:
        self.detection_score = 0.
    else:
      self.id = 0
      self.dictionary_name = ''
      self.corners_px = []
      self.center_px = geometry_msgs.msg.Point32()
      self.tag_area_px = 0.
      self.detection_score = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.id
      buff.write(_get_struct_i().pack(_x))
      _x = self.dictionary_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.corners_px)
      buff.write(_struct_I.pack(length))
      for val1 in self.corners_px:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      _x = self
      buff.write(_get_struct_5f().pack(_x.center_px.x, _x.center_px.y, _x.center_px.z, _x.tag_area_px, _x.detection_score))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.corners_px is None:
        self.corners_px = None
      if self.center_px is None:
        self.center_px = geometry_msgs.msg.Point32()
      end = 0
      start = end
      end += 4
      (self.id,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.dictionary_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.dictionary_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.corners_px = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point32()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.corners_px.append(val1)
      _x = self
      start = end
      end += 20
      (_x.center_px.x, _x.center_px.y, _x.center_px.z, _x.tag_area_px, _x.detection_score,) = _get_struct_5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.id
      buff.write(_get_struct_i().pack(_x))
      _x = self.dictionary_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.corners_px)
      buff.write(_struct_I.pack(length))
      for val1 in self.corners_px:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      _x = self
      buff.write(_get_struct_5f().pack(_x.center_px.x, _x.center_px.y, _x.center_px.z, _x.tag_area_px, _x.detection_score))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.corners_px is None:
        self.corners_px = None
      if self.center_px is None:
        self.center_px = geometry_msgs.msg.Point32()
      end = 0
      start = end
      end += 4
      (self.id,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.dictionary_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.dictionary_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.corners_px = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point32()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.corners_px.append(val1)
      _x = self
      start = end
      end += 20
      (_x.center_px.x, _x.center_px.y, _x.center_px.z, _x.tag_area_px, _x.detection_score,) = _get_struct_5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_5f = None
def _get_struct_5f():
    global _struct_5f
    if _struct_5f is None:
        _struct_5f = struct.Struct("<5f")
    return _struct_5f
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
