(cl:defpackage assistive_msgs-msg
  (:use )
  (:export
   "<STATE2D>"
   "STATE2D"
   "<TAGDEPTHOBSERVATION>"
   "TAGDEPTHOBSERVATION"
   "<TAGDEPTHOBSERVATIONARRAY>"
   "TAGDEPTHOBSERVATIONARRAY"
   "<TAGDETECTION>"
   "TAGDETECTION"
   "<TAGDETECTIONARRAY>"
   "TAGDETECTIONARRAY"
   "<TAGPOSE>"
   "TAGPOSE"
   "<TAGPOSEARRAY>"
   "TAGPOSEARRAY"
  ))

