// Generated by gencpp from file assistive_msgs/TagDetectionArray.msg
// DO NOT EDIT!


#ifndef ASSISTIVE_MSGS_MESSAGE_TAGDETECTIONARRAY_H
#define ASSISTIVE_MSGS_MESSAGE_TAGDETECTIONARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <assistive_msgs/TagDetection.h>

namespace assistive_msgs
{
template <class ContainerAllocator>
struct TagDetectionArray_
{
  typedef TagDetectionArray_<ContainerAllocator> Type;

  TagDetectionArray_()
    : header()
    , image_width(0)
    , image_height(0)
    , detections()  {
    }
  TagDetectionArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , image_width(0)
    , image_height(0)
    , detections(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _image_width_type;
  _image_width_type image_width;

   typedef uint32_t _image_height_type;
  _image_height_type image_height;

   typedef std::vector< ::assistive_msgs::TagDetection_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::assistive_msgs::TagDetection_<ContainerAllocator> >> _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::assistive_msgs::TagDetectionArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assistive_msgs::TagDetectionArray_<ContainerAllocator> const> ConstPtr;

}; // struct TagDetectionArray_

typedef ::assistive_msgs::TagDetectionArray_<std::allocator<void> > TagDetectionArray;

typedef boost::shared_ptr< ::assistive_msgs::TagDetectionArray > TagDetectionArrayPtr;
typedef boost::shared_ptr< ::assistive_msgs::TagDetectionArray const> TagDetectionArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assistive_msgs::TagDetectionArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assistive_msgs::TagDetectionArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assistive_msgs::TagDetectionArray_<ContainerAllocator1> & lhs, const ::assistive_msgs::TagDetectionArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.image_width == rhs.image_width &&
    lhs.image_height == rhs.image_height &&
    lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assistive_msgs::TagDetectionArray_<ContainerAllocator1> & lhs, const ::assistive_msgs::TagDetectionArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assistive_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assistive_msgs::TagDetectionArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assistive_msgs::TagDetectionArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assistive_msgs::TagDetectionArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assistive_msgs::TagDetectionArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assistive_msgs::TagDetectionArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assistive_msgs::TagDetectionArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assistive_msgs::TagDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a03b80106751ad8d398be0566d903e79";
  }

  static const char* value(const ::assistive_msgs::TagDetectionArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa03b80106751ad8dULL;
  static const uint64_t static_value2 = 0x398be0566d903e79ULL;
};

template<class ContainerAllocator>
struct DataType< ::assistive_msgs::TagDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assistive_msgs/TagDetectionArray";
  }

  static const char* value(const ::assistive_msgs::TagDetectionArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assistive_msgs::TagDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"uint32 image_width\n"
"uint32 image_height\n"
"TagDetection[] detections\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: assistive_msgs/TagDetection\n"
"int32 id\n"
"string dictionary_name\n"
"geometry_msgs/Point32[] corners_px\n"
"geometry_msgs/Point32 center_px\n"
"float32 tag_area_px\n"
"float32 detection_score\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::assistive_msgs::TagDetectionArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assistive_msgs::TagDetectionArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.image_width);
      stream.next(m.image_height);
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TagDetectionArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assistive_msgs::TagDetectionArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assistive_msgs::TagDetectionArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "image_width: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.image_width);
    s << indent << "image_height: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.image_height);
    s << indent << "detections[]" << std::endl;
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      s << indent << "  detections[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::assistive_msgs::TagDetection_<ContainerAllocator> >::stream(s, indent + "    ", v.detections[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSISTIVE_MSGS_MESSAGE_TAGDETECTIONARRAY_H
