// Generated by gencpp from file assistive_msgs/TagDepthObservation.msg
// DO NOT EDIT!


#ifndef ASSISTIVE_MSGS_MESSAGE_TAGDEPTHOBSERVATION_H
#define ASSISTIVE_MSGS_MESSAGE_TAGDEPTHOBSERVATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>

namespace assistive_msgs
{
template <class ContainerAllocator>
struct TagDepthObservation_
{
  typedef TagDepthObservation_<ContainerAllocator> Type;

  TagDepthObservation_()
    : id(0)
    , center_cam()
    , normal_cam()
    , mean_depth_m(0.0)
    , valid_point_ratio(0.0)
    , support_point_count(0)
    , plane_fitted(false)  {
    }
  TagDepthObservation_(const ContainerAllocator& _alloc)
    : id(0)
    , center_cam(_alloc)
    , normal_cam(_alloc)
    , mean_depth_m(0.0)
    , valid_point_ratio(0.0)
    , support_point_count(0)
    , plane_fitted(false)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _center_cam_type;
  _center_cam_type center_cam;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _normal_cam_type;
  _normal_cam_type normal_cam;

   typedef float _mean_depth_m_type;
  _mean_depth_m_type mean_depth_m;

   typedef float _valid_point_ratio_type;
  _valid_point_ratio_type valid_point_ratio;

   typedef uint32_t _support_point_count_type;
  _support_point_count_type support_point_count;

   typedef uint8_t _plane_fitted_type;
  _plane_fitted_type plane_fitted;





  typedef boost::shared_ptr< ::assistive_msgs::TagDepthObservation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assistive_msgs::TagDepthObservation_<ContainerAllocator> const> ConstPtr;

}; // struct TagDepthObservation_

typedef ::assistive_msgs::TagDepthObservation_<std::allocator<void> > TagDepthObservation;

typedef boost::shared_ptr< ::assistive_msgs::TagDepthObservation > TagDepthObservationPtr;
typedef boost::shared_ptr< ::assistive_msgs::TagDepthObservation const> TagDepthObservationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assistive_msgs::TagDepthObservation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assistive_msgs::TagDepthObservation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assistive_msgs::TagDepthObservation_<ContainerAllocator1> & lhs, const ::assistive_msgs::TagDepthObservation_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.center_cam == rhs.center_cam &&
    lhs.normal_cam == rhs.normal_cam &&
    lhs.mean_depth_m == rhs.mean_depth_m &&
    lhs.valid_point_ratio == rhs.valid_point_ratio &&
    lhs.support_point_count == rhs.support_point_count &&
    lhs.plane_fitted == rhs.plane_fitted;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assistive_msgs::TagDepthObservation_<ContainerAllocator1> & lhs, const ::assistive_msgs::TagDepthObservation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assistive_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assistive_msgs::TagDepthObservation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assistive_msgs::TagDepthObservation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assistive_msgs::TagDepthObservation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assistive_msgs::TagDepthObservation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assistive_msgs::TagDepthObservation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assistive_msgs::TagDepthObservation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assistive_msgs::TagDepthObservation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4196ac7d305dd54a89c13071539bb080";
  }

  static const char* value(const ::assistive_msgs::TagDepthObservation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4196ac7d305dd54aULL;
  static const uint64_t static_value2 = 0x89c13071539bb080ULL;
};

template<class ContainerAllocator>
struct DataType< ::assistive_msgs::TagDepthObservation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assistive_msgs/TagDepthObservation";
  }

  static const char* value(const ::assistive_msgs::TagDepthObservation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assistive_msgs::TagDepthObservation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"geometry_msgs/Point center_cam\n"
"geometry_msgs/Vector3 normal_cam\n"
"float32 mean_depth_m\n"
"float32 valid_point_ratio\n"
"uint32 support_point_count\n"
"bool plane_fitted\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::assistive_msgs::TagDepthObservation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assistive_msgs::TagDepthObservation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.center_cam);
      stream.next(m.normal_cam);
      stream.next(m.mean_depth_m);
      stream.next(m.valid_point_ratio);
      stream.next(m.support_point_count);
      stream.next(m.plane_fitted);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TagDepthObservation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assistive_msgs::TagDepthObservation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assistive_msgs::TagDepthObservation_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "center_cam: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.center_cam);
    s << indent << "normal_cam: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.normal_cam);
    s << indent << "mean_depth_m: ";
    Printer<float>::stream(s, indent + "  ", v.mean_depth_m);
    s << indent << "valid_point_ratio: ";
    Printer<float>::stream(s, indent + "  ", v.valid_point_ratio);
    s << indent << "support_point_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.support_point_count);
    s << indent << "plane_fitted: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.plane_fitted);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSISTIVE_MSGS_MESSAGE_TAGDEPTHOBSERVATION_H
