// Generated by gencpp from file assistive_msgs/TagDepthObservationArray.msg
// DO NOT EDIT!


#ifndef ASSISTIVE_MSGS_MESSAGE_TAGDEPTHOBSERVATIONARRAY_H
#define ASSISTIVE_MSGS_MESSAGE_TAGDEPTHOBSERVATIONARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <assistive_msgs/TagDepthObservation.h>

namespace assistive_msgs
{
template <class ContainerAllocator>
struct TagDepthObservationArray_
{
  typedef TagDepthObservationArray_<ContainerAllocator> Type;

  TagDepthObservationArray_()
    : header()
    , observations()  {
    }
  TagDepthObservationArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , observations(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::assistive_msgs::TagDepthObservation_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::assistive_msgs::TagDepthObservation_<ContainerAllocator> >> _observations_type;
  _observations_type observations;





  typedef boost::shared_ptr< ::assistive_msgs::TagDepthObservationArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assistive_msgs::TagDepthObservationArray_<ContainerAllocator> const> ConstPtr;

}; // struct TagDepthObservationArray_

typedef ::assistive_msgs::TagDepthObservationArray_<std::allocator<void> > TagDepthObservationArray;

typedef boost::shared_ptr< ::assistive_msgs::TagDepthObservationArray > TagDepthObservationArrayPtr;
typedef boost::shared_ptr< ::assistive_msgs::TagDepthObservationArray const> TagDepthObservationArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assistive_msgs::TagDepthObservationArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assistive_msgs::TagDepthObservationArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assistive_msgs::TagDepthObservationArray_<ContainerAllocator1> & lhs, const ::assistive_msgs::TagDepthObservationArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.observations == rhs.observations;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assistive_msgs::TagDepthObservationArray_<ContainerAllocator1> & lhs, const ::assistive_msgs::TagDepthObservationArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assistive_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assistive_msgs::TagDepthObservationArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assistive_msgs::TagDepthObservationArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assistive_msgs::TagDepthObservationArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assistive_msgs::TagDepthObservationArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assistive_msgs::TagDepthObservationArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assistive_msgs::TagDepthObservationArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assistive_msgs::TagDepthObservationArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d36ffe9c694665b938ccaa32e775bddb";
  }

  static const char* value(const ::assistive_msgs::TagDepthObservationArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd36ffe9c694665b9ULL;
  static const uint64_t static_value2 = 0x38ccaa32e775bddbULL;
};

template<class ContainerAllocator>
struct DataType< ::assistive_msgs::TagDepthObservationArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assistive_msgs/TagDepthObservationArray";
  }

  static const char* value(const ::assistive_msgs::TagDepthObservationArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assistive_msgs::TagDepthObservationArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"TagDepthObservation[] observations\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: assistive_msgs/TagDepthObservation\n"
"int32 id\n"
"geometry_msgs/Point center_cam\n"
"geometry_msgs/Vector3 normal_cam\n"
"float32 mean_depth_m\n"
"float32 valid_point_ratio\n"
"uint32 support_point_count\n"
"bool plane_fitted\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::assistive_msgs::TagDepthObservationArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assistive_msgs::TagDepthObservationArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.observations);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TagDepthObservationArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assistive_msgs::TagDepthObservationArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assistive_msgs::TagDepthObservationArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "observations[]" << std::endl;
    for (size_t i = 0; i < v.observations.size(); ++i)
    {
      s << indent << "  observations[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::assistive_msgs::TagDepthObservation_<ContainerAllocator> >::stream(s, indent + "    ", v.observations[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSISTIVE_MSGS_MESSAGE_TAGDEPTHOBSERVATIONARRAY_H
