// Generated by gencpp from file assistive_msgs/TagDetection.msg
// DO NOT EDIT!


#ifndef ASSISTIVE_MSGS_MESSAGE_TAGDETECTION_H
#define ASSISTIVE_MSGS_MESSAGE_TAGDETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point32.h>
#include <geometry_msgs/Point32.h>

namespace assistive_msgs
{
template <class ContainerAllocator>
struct TagDetection_
{
  typedef TagDetection_<ContainerAllocator> Type;

  TagDetection_()
    : id(0)
    , dictionary_name()
    , corners_px()
    , center_px()
    , tag_area_px(0.0)
    , detection_score(0.0)  {
    }
  TagDetection_(const ContainerAllocator& _alloc)
    : id(0)
    , dictionary_name(_alloc)
    , corners_px(_alloc)
    , center_px(_alloc)
    , tag_area_px(0.0)
    , detection_score(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _dictionary_name_type;
  _dictionary_name_type dictionary_name;

   typedef std::vector< ::geometry_msgs::Point32_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point32_<ContainerAllocator> >> _corners_px_type;
  _corners_px_type corners_px;

   typedef  ::geometry_msgs::Point32_<ContainerAllocator>  _center_px_type;
  _center_px_type center_px;

   typedef float _tag_area_px_type;
  _tag_area_px_type tag_area_px;

   typedef float _detection_score_type;
  _detection_score_type detection_score;





  typedef boost::shared_ptr< ::assistive_msgs::TagDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assistive_msgs::TagDetection_<ContainerAllocator> const> ConstPtr;

}; // struct TagDetection_

typedef ::assistive_msgs::TagDetection_<std::allocator<void> > TagDetection;

typedef boost::shared_ptr< ::assistive_msgs::TagDetection > TagDetectionPtr;
typedef boost::shared_ptr< ::assistive_msgs::TagDetection const> TagDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assistive_msgs::TagDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assistive_msgs::TagDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assistive_msgs::TagDetection_<ContainerAllocator1> & lhs, const ::assistive_msgs::TagDetection_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.dictionary_name == rhs.dictionary_name &&
    lhs.corners_px == rhs.corners_px &&
    lhs.center_px == rhs.center_px &&
    lhs.tag_area_px == rhs.tag_area_px &&
    lhs.detection_score == rhs.detection_score;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assistive_msgs::TagDetection_<ContainerAllocator1> & lhs, const ::assistive_msgs::TagDetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assistive_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assistive_msgs::TagDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assistive_msgs::TagDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assistive_msgs::TagDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assistive_msgs::TagDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assistive_msgs::TagDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assistive_msgs::TagDetection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assistive_msgs::TagDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be3ec919f3e7b8dc86da70562d16b37e";
  }

  static const char* value(const ::assistive_msgs::TagDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe3ec919f3e7b8dcULL;
  static const uint64_t static_value2 = 0x86da70562d16b37eULL;
};

template<class ContainerAllocator>
struct DataType< ::assistive_msgs::TagDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assistive_msgs/TagDetection";
  }

  static const char* value(const ::assistive_msgs::TagDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assistive_msgs::TagDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"string dictionary_name\n"
"geometry_msgs/Point32[] corners_px\n"
"geometry_msgs/Point32 center_px\n"
"float32 tag_area_px\n"
"float32 detection_score\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::assistive_msgs::TagDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assistive_msgs::TagDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.dictionary_name);
      stream.next(m.corners_px);
      stream.next(m.center_px);
      stream.next(m.tag_area_px);
      stream.next(m.detection_score);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TagDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assistive_msgs::TagDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assistive_msgs::TagDetection_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "dictionary_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.dictionary_name);
    s << indent << "corners_px[]" << std::endl;
    for (size_t i = 0; i < v.corners_px.size(); ++i)
    {
      s << indent << "  corners_px[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "    ", v.corners_px[i]);
    }
    s << indent << "center_px: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "  ", v.center_px);
    s << indent << "tag_area_px: ";
    Printer<float>::stream(s, indent + "  ", v.tag_area_px);
    s << indent << "detection_score: ";
    Printer<float>::stream(s, indent + "  ", v.detection_score);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSISTIVE_MSGS_MESSAGE_TAGDETECTION_H
