// Generated by gencpp from file assistive_msgs/TagPoseArray.msg
// DO NOT EDIT!


#ifndef ASSISTIVE_MSGS_MESSAGE_TAGPOSEARRAY_H
#define ASSISTIVE_MSGS_MESSAGE_TAGPOSEARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <assistive_msgs/TagPose.h>

namespace assistive_msgs
{
template <class ContainerAllocator>
struct TagPoseArray_
{
  typedef TagPoseArray_<ContainerAllocator> Type;

  TagPoseArray_()
    : header()
    , poses()  {
    }
  TagPoseArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , poses(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::assistive_msgs::TagPose_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::assistive_msgs::TagPose_<ContainerAllocator> >> _poses_type;
  _poses_type poses;





  typedef boost::shared_ptr< ::assistive_msgs::TagPoseArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assistive_msgs::TagPoseArray_<ContainerAllocator> const> ConstPtr;

}; // struct TagPoseArray_

typedef ::assistive_msgs::TagPoseArray_<std::allocator<void> > TagPoseArray;

typedef boost::shared_ptr< ::assistive_msgs::TagPoseArray > TagPoseArrayPtr;
typedef boost::shared_ptr< ::assistive_msgs::TagPoseArray const> TagPoseArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assistive_msgs::TagPoseArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assistive_msgs::TagPoseArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assistive_msgs::TagPoseArray_<ContainerAllocator1> & lhs, const ::assistive_msgs::TagPoseArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.poses == rhs.poses;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assistive_msgs::TagPoseArray_<ContainerAllocator1> & lhs, const ::assistive_msgs::TagPoseArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assistive_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assistive_msgs::TagPoseArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assistive_msgs::TagPoseArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assistive_msgs::TagPoseArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assistive_msgs::TagPoseArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assistive_msgs::TagPoseArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assistive_msgs::TagPoseArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assistive_msgs::TagPoseArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c3cca4e7646ea151147453dc311444c2";
  }

  static const char* value(const ::assistive_msgs::TagPoseArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc3cca4e7646ea151ULL;
  static const uint64_t static_value2 = 0x147453dc311444c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::assistive_msgs::TagPoseArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assistive_msgs/TagPoseArray";
  }

  static const char* value(const ::assistive_msgs::TagPoseArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assistive_msgs::TagPoseArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"TagPose[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: assistive_msgs/TagPose\n"
"int32 id\n"
"string dictionary_name\n"
"geometry_msgs/PoseWithCovariance pose\n"
"geometry_msgs/Vector3 normal\n"
"bool observed\n"
"float32 tag_area_px\n"
"float32 detection_score\n"
"float32 reprojection_error_px\n"
"bool depth_fused\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::assistive_msgs::TagPoseArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assistive_msgs::TagPoseArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.poses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TagPoseArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assistive_msgs::TagPoseArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assistive_msgs::TagPoseArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::assistive_msgs::TagPose_<ContainerAllocator> >::stream(s, indent + "    ", v.poses[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSISTIVE_MSGS_MESSAGE_TAGPOSEARRAY_H
