// Generated by gencpp from file assistive_msgs/TagPose.msg
// DO NOT EDIT!


#ifndef ASSISTIVE_MSGS_MESSAGE_TAGPOSE_H
#define ASSISTIVE_MSGS_MESSAGE_TAGPOSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseWithCovariance.h>
#include <geometry_msgs/Vector3.h>

namespace assistive_msgs
{
template <class ContainerAllocator>
struct TagPose_
{
  typedef TagPose_<ContainerAllocator> Type;

  TagPose_()
    : id(0)
    , dictionary_name()
    , pose()
    , normal()
    , observed(false)
    , tag_area_px(0.0)
    , detection_score(0.0)
    , reprojection_error_px(0.0)
    , depth_fused(false)  {
    }
  TagPose_(const ContainerAllocator& _alloc)
    : id(0)
    , dictionary_name(_alloc)
    , pose(_alloc)
    , normal(_alloc)
    , observed(false)
    , tag_area_px(0.0)
    , detection_score(0.0)
    , reprojection_error_px(0.0)
    , depth_fused(false)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _dictionary_name_type;
  _dictionary_name_type dictionary_name;

   typedef  ::geometry_msgs::PoseWithCovariance_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _normal_type;
  _normal_type normal;

   typedef uint8_t _observed_type;
  _observed_type observed;

   typedef float _tag_area_px_type;
  _tag_area_px_type tag_area_px;

   typedef float _detection_score_type;
  _detection_score_type detection_score;

   typedef float _reprojection_error_px_type;
  _reprojection_error_px_type reprojection_error_px;

   typedef uint8_t _depth_fused_type;
  _depth_fused_type depth_fused;





  typedef boost::shared_ptr< ::assistive_msgs::TagPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assistive_msgs::TagPose_<ContainerAllocator> const> ConstPtr;

}; // struct TagPose_

typedef ::assistive_msgs::TagPose_<std::allocator<void> > TagPose;

typedef boost::shared_ptr< ::assistive_msgs::TagPose > TagPosePtr;
typedef boost::shared_ptr< ::assistive_msgs::TagPose const> TagPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assistive_msgs::TagPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assistive_msgs::TagPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assistive_msgs::TagPose_<ContainerAllocator1> & lhs, const ::assistive_msgs::TagPose_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.dictionary_name == rhs.dictionary_name &&
    lhs.pose == rhs.pose &&
    lhs.normal == rhs.normal &&
    lhs.observed == rhs.observed &&
    lhs.tag_area_px == rhs.tag_area_px &&
    lhs.detection_score == rhs.detection_score &&
    lhs.reprojection_error_px == rhs.reprojection_error_px &&
    lhs.depth_fused == rhs.depth_fused;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assistive_msgs::TagPose_<ContainerAllocator1> & lhs, const ::assistive_msgs::TagPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assistive_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assistive_msgs::TagPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assistive_msgs::TagPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assistive_msgs::TagPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assistive_msgs::TagPose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assistive_msgs::TagPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assistive_msgs::TagPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assistive_msgs::TagPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0f26474302ad493af59fa06f6d81f35b";
  }

  static const char* value(const ::assistive_msgs::TagPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0f26474302ad493aULL;
  static const uint64_t static_value2 = 0xf59fa06f6d81f35bULL;
};

template<class ContainerAllocator>
struct DataType< ::assistive_msgs::TagPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assistive_msgs/TagPose";
  }

  static const char* value(const ::assistive_msgs::TagPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assistive_msgs::TagPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"string dictionary_name\n"
"geometry_msgs/PoseWithCovariance pose\n"
"geometry_msgs/Vector3 normal\n"
"bool observed\n"
"float32 tag_area_px\n"
"float32 detection_score\n"
"float32 reprojection_error_px\n"
"bool depth_fused\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::assistive_msgs::TagPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assistive_msgs::TagPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.dictionary_name);
      stream.next(m.pose);
      stream.next(m.normal);
      stream.next(m.observed);
      stream.next(m.tag_area_px);
      stream.next(m.detection_score);
      stream.next(m.reprojection_error_px);
      stream.next(m.depth_fused);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TagPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assistive_msgs::TagPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assistive_msgs::TagPose_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "dictionary_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.dictionary_name);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseWithCovariance_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "normal: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.normal);
    s << indent << "observed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.observed);
    s << indent << "tag_area_px: ";
    Printer<float>::stream(s, indent + "  ", v.tag_area_px);
    s << indent << "detection_score: ";
    Printer<float>::stream(s, indent + "  ", v.detection_score);
    s << indent << "reprojection_error_px: ";
    Printer<float>::stream(s, indent + "  ", v.reprojection_error_px);
    s << indent << "depth_fused: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.depth_fused);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSISTIVE_MSGS_MESSAGE_TAGPOSE_H
